version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: weather-postgres
    environment:
      - POSTGRES_USER=weatheruser
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: 