version: "3.8"

services:
  weather_etl:
    container_name: weather-etl
    build:
      context: .
      args:
        - IMAGE_TAG=${IMAGE_TAG:-latest}
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    image: ${DOCKERHUB_USERNAME:-yourusername}/weather-etl:${IMAGE_TAG:-latest}
    working_dir: /app
    env_file:
      - .env
    # Network mode to allow connecting to host's Docker network
    network_mode: "host"
    